spring.application.name=RestAPI

#Port configuration
server.port=8080

# DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

# This allows the direct /swagger-ui/index.html access
springdoc.swagger-ui.path=/index.html

# This file do not accept comments after set variables - do not add comments